// Hand-written TypeScript material with no Rust source, plus small helper
// functions/consts that used to live inline in the 6 files now generated by
// crates/athenaeum-core/src/ts_export.rs (see .superpowers/sdd/p1-ts-inventory.md
// for the full TS-ONLY classification — 68 declarations, all relocated here).
//
// Also carries `...Values` companion objects for former TS `enum`s that are
// referenced as VALUES elsewhere in the frontend (`ImageType`, `MatchMode`,
// `MasterPreference`) — ts-rs derives string-literal unions, not TS enums, so
// there is no runtime object to reference (`ImageType.Light` no longer
// exists; use `ImageTypeValues.Light`). Values are copied verbatim from the
// generated unions in ./models and ./calibration-config, not from memory.
//
// Import direction is one-way: this file imports types FROM the generated
// files below, never the reverse.

import type {
  ImageType,
  FramesSet,
  ScanRoot,
  CalendarMonthData,
} from './models';
import type { ArchiveCompression, FrameRole } from './archive';
import type { MatchMode, ParameterConfig, MasterPreference } from './calibration-config';
import type { AutofindStatus } from './plate-solve';
import type { AnnotationSettings } from './analysis-config';

// ============================================================================
// models.ts TS-ONLY material
// ============================================================================

export interface BlackholeChangedEvent {
  file_id: number;
  action: 'blackholed' | 'restored';
}

/** Companion object for the generated `ImageType` string-literal union
 *  (models.rs `ImageType`, serde default variant naming — no rename_all).
 *  Variant strings copied from the generated `models.ts` union, which added
 *  `MasterLight` since the old hand-written enum was last updated. */
export const ImageTypeValues = {
  Light: 'Light',
  Dark: 'Dark',
  Flat: 'Flat',
  Bias: 'Bias',
  DarkFlat: 'DarkFlat',
  MasterLight: 'MasterLight',
  MasterDark: 'MasterDark',
  MasterFlat: 'MasterFlat',
  MasterBias: 'MasterBias',
  MasterDarkFlat: 'MasterDarkFlat',
} as const satisfies Record<string, ImageType>;

// Helper function to check if an imagetyp is a master type
export function isMasterType(imagetyp: ImageType | string): boolean {
  return (
    imagetyp === ImageTypeValues.MasterDark ||
    imagetyp === ImageTypeValues.MasterFlat ||
    imagetyp === ImageTypeValues.MasterBias ||
    imagetyp === ImageTypeValues.MasterDarkFlat
  );
}

export interface ScanRootWithAvailability extends ScanRoot {
  is_available: boolean;
}

// ── Duplicates picker rule chain ─────────────────────────────────────────────
//
// The duplicates view auto-marks files for deletion using an ordered chain of
// rules. Each rule either picks a deletion set for a group or abstains; the
// first non-abstaining rule wins per group. A rule that would mark every file
// in a group also abstains (safety) so we never produce a group with no
// keepers.

export type RuleKind =
  | 'master_root'
  | 'path_contains'
  | 'oldest_mtime'
  | 'shortest_path';

interface BaseRule {
  enabled: boolean;
}

export interface MasterRootRule extends BaseRule {
  kind: 'master_root';
  config: { rootId: number | null };
}

export interface PathContainsRule extends BaseRule {
  kind: 'path_contains';
  /** `negate` flips the rule: with it on, the deletion set is the files whose
   *  path contains NONE of the patterns. */
  config: { patterns: string[]; caseSensitive: boolean; negate: boolean };
}

export interface OldestMtimeRule extends BaseRule {
  kind: 'oldest_mtime';
  config: Record<string, never>;
}

export interface ShortestPathRule extends BaseRule {
  kind: 'shortest_path';
  config: Record<string, never>;
}

export type Rule =
  | MasterRootRule
  | PathContainsRule
  | OldestMtimeRule
  | ShortestPathRule;

export type RuleChain = Rule[];

// DTOs for Tauri commands
export interface ScanResult {
  files_found: number;
  files_processed: number;
  files_skipped: number;
  errors: string[];
  // Frame type counts
  lights_count: number;
  darks_count: number;
  flats_count: number;
  bias_count: number;
  darkflats_count: number;
  // Calibration sets created
  calibration_sets_created: number;
  // Unique camera reconciliation stats (non-zero when instrume suffix state changed during rescan)
  frames_renamed: number;
  calibration_sets_deleted: number;
  sessions_updated: number;
  // Whether scan was cancelled by user
  cancelled: boolean;
}

// Frame Sets DTOs
export interface AutoGenerateResult {
  sets_created: number;
  frames_clustered: number;
  frames_excluded: number;
  frames_already_in_sets: number;
  exclusion_reasons: string[];
}

export interface FramesSetWithCount {
  frames_set: FramesSet;
  member_count: number;
}

// Missing file record with status from the database
export interface MissingFileRecord {
  id: number;
  file_id: number;
  scan_root_id: number;
  detected_at: string;
  last_checked_at: string;
  status: 'missing' | 'ignored';
  // File info
  path: string;
  filename: string;
  size: number;
  modified_at: string;
  // Frame info (if exists)
  has_frame: boolean;
  object: string | null;
  date_obs: string | null;
}

export interface CalendarYearData {
  year: number;
  months: CalendarMonthData[]; // Only months with data
  totalFrameCount: number;
  totalExposureSeconds: number;
}

/** Result of batch frame set analysis */
export interface AnalyzeFrameSetResult {
  analyzed: number;
  skipped: number;
  failed: number;
  errors: string[];
  cancelled: boolean;
}

/** Analysis progress event emitted during batch analysis */
export interface AnalysisProgressEvent {
  frame_set_id: number;
  current: number;
  total: number;
  current_file: string;
  percent: number;
}

/** Analysis complete event emitted when a frame set analysis finishes */
export interface AnalysisCompleteEvent {
  frame_set_id: number;
  analyzed: number;
  skipped: number;
  failed: number;
  errors: string[];
  cancelled: boolean;
}

/** Progress event emitted during a master build (`master-build-progress`).
 *  `stage` documents the full backend contract including `'reading'`
 *  (reserved for future use — member-path enumeration is cheap enough today
 *  not to need its own tick, so the backend never actually emits it; see
 *  `athenaeum-core/src/api/masters.rs`'s `MasterBuildProgressEvent` doc
 *  comment) and `'combining'` (fix wave item 2: ticks during the per-pixel
 *  combine phase that follows a band's read, so a build the memory budget
 *  resolves to a single band does not freeze the UI at 100% for however
 *  long that band's combine takes — see
 *  `athenaeum-core/src/integration/engine.rs`'s `EngineProgress::on_combine`
 *  doc). Consumers must not assume every listed stage will arrive. */
export interface MasterBuildProgressEvent {
  set_id: number;
  stage: 'reading' | 'integrating' | 'combining' | 'writing' | 'registering';
  current: number;
  total: number;
  /** One monotonic 0-100 across the whole pixel phase: reading (bytes) is
   *  weighted 0.7, combining (rows) 0.3 — see `build_percent` in
   *  `athenaeum-core/src/api/masters.rs`. Never goes backwards between
   *  `'integrating'` and `'combining'`; `'writing'`/`'registering'` report 0. */
  percent: number;
  /** Bytes of source read so far / in total. `current`/`total` count bands,
   *  which say nothing about size once bands are machine-sized — EXCEPT
   *  during the `'combining'` stage, where `current`/`total` count rows
   *  instead and `bytes_done`/`bytes_total` are frozen at whatever
   *  `'integrating'` last reported (combine reads nothing new). */
  bytes_done: number;
  bytes_total: number;
}

/** Completion event for a master build (`master-build-complete`). ALWAYS
 *  emitted exactly once per `start_master_build` call regardless of outcome
 *  (success, error, cancelled). `set_id` is the SOURCE calibration set id,
 *  not `master_set_id` — see the Rust doc comment for why (rebuild keys off
 *  the same source set).
 *
 *  `warning` is the non-fatal counterpart of `error`: the build succeeded but
 *  the source data had something worth reporting (today: non-finite samples
 *  excluded from the integration). Optional because the hook also synthesizes
 *  local failure events that never carry one. */
export interface MasterBuildCompleteEvent {
  set_id: number;
  master_set_id: number | null;
  success: boolean;
  cancelled: boolean;
  error: string | null;
  warning?: string | null;
}

/** Response from `compute_flat_contour_plot`. The `pixelsB64` field is the
 *  final 8-bit grayscale display image (length == width*height) base64-
 *  encoded for JSON transport. The frontend paints those bytes directly
 *  via putImageData; the legend strip is built from `minQuantile`,
 *  `maxQuantile`, and `contours`. */
export interface FlatContourPlot {
  width: number;
  height: number;
  /** Raw-units peak of the resampled, pre-rescale image. */
  peak: number;
  /** Raw-units mean. */
  mean: number;
  /** Raw-units min. */
  min: number;
  /** 1st-percentile sample value (legend low edge, original flat units). */
  minQuantile: number;
  /** 99th-percentile sample value (legend high edge, original flat units). */
  maxQuantile: number;
  /** Echoed back from the request — number of bands the result uses. */
  contours: number;
  /** Base64-encoded 8-bit grayscale buffer. */
  pixelsB64: string;
}

// ============================================================================
// archive.ts TS-ONLY material
// ============================================================================

export interface ArchiveSettings {
  rootPath: string | null;
  compression: ArchiveCompression;
}

export interface ArchivedFrameSetSummary {
  frames_set_id: number;
  name: string | null;
  archived_at: string | null;
  operation_id: number | null;
  archive_root_path: string | null;
  started_at: string | null;
  lights_count: number;
  flats_count: number;
  darks_count: number;
  bias_count: number;
  darkflats_count: number;
}

export interface ArchiveProgressEvent {
  operation_id: number;
  stage: string;
  current: number;
  total: number;
  message: string;
}

export interface ArchiveRoot {
  id: number;
  path: string;
  label: string | null;
  is_default: boolean;
}

export interface ArchiveZip {
  path: string;
  filename: string;
  frame_role: FrameRole | string;
  exists: boolean;
  size_bytes: number;
}

// ============================================================================
// export.ts TS-ONLY material
// ============================================================================

/** Frame set summary for export selection */
export interface ExportableFrameSet {
  id: number;
  name: string | null;
  totalExposureSeconds: number;
  frameCount: number;
  objectName: string | null;
  filters: string[];
}

// ============================================================================
// calibration-config.ts TS-ONLY material
// ============================================================================

/** Companion object for the generated `MatchMode` string-literal union
 *  (calibration/config.rs `MatchMode`, serde `rename_all = "lowercase"`). */
export const MatchModeValues = {
  Exact: 'exact',
  Warning: 'warning',
  Ignore: 'ignore',
} as const satisfies Record<string, MatchMode>;

/** Companion object for the generated `MasterPreference` string-literal union
 *  (calibration/config.rs `MasterPreference`, serde `rename_all = "snake_case"`). */
export const MasterPreferenceValues = {
  PreferMaster: 'prefer_master',
  PreferFrameset: 'prefer_frameset',
  NoPreference: 'no_preference',
} as const satisfies Record<string, MasterPreference>;

/** Validate that warning_threshold <= matching_threshold */
export function validateThresholds(config: ParameterConfig): string | null {
  if (config.mode === MatchModeValues.Warning) {
    const warn = config.warning_threshold ?? 0;
    const match = config.matching_threshold ?? Infinity;
    if (warn > match) {
      return `Warning threshold (${warn}) cannot be greater than matching threshold (${match})`;
    }
  }
  return null;
}

/** Get display label for a parameter */
export function getParameterLabel(param: string): string {
  const labels: Record<string, string> = {
    instrume: "Camera",
    binning: "Binning",
    gain: "Gain",
    offset: "Offset",
    telescop: "Telescope",
    exptime: "Exposure",
    focallen: "Focal Length",
    filter: "Filter",
    ccd_temp: "CCD Temp",
  };
  return labels[param] || param;
}

/** Parameters that support warning mode with dual thresholds */
export const WARNING_CAPABLE_PARAMETERS = [
  "exptime",
  "focallen",
  "ccd_temp",
] as const;

/** All configurable parameters */
export const CONFIGURABLE_PARAMETERS = [
  "instrume",
  "binning",
  "gain",
  "offset",
  "telescop",
  "exptime",
  "focallen",
  "filter",
  "ccd_temp",
] as const;

export type WarningCapableParameter =
  (typeof WARNING_CAPABLE_PARAMETERS)[number];

/** Check if a parameter supports warning mode */
export function supportsWarningMode(
  param: string
): param is WarningCapableParameter {
  return (WARNING_CAPABLE_PARAMETERS as readonly string[]).includes(param);
}

// ============================================================================
// plate-solve.ts TS-ONLY material
// ============================================================================

export interface PlateSolveProgressEvent {
  frame_id: number;
  current: number;
  total: number;
  status: "solving" | "solved" | "failed";
  matched_stars?: number;
  rms_arcsec?: number;
  error?: string;
  /** Machine code for a failure (solvemyastro FailureClass, e.g. "VERIFY_GAP",
   * or "REJECTED_LOW_CONFIDENCE" / "PANIC"). Lets the UI group/style reasons. */
  failure_code?: string;
  /** Frame filename, for labelling per-frame rows without a separate lookup. */
  filename?: string;
}

export interface PlateSolveCompleteEvent {
  solved: number;
  failed: number;
  total: number;
  total_time_ms: number;
}

export interface CatalogStatusInfo {
  name: string;
  density: number;
  installed: boolean;
  epoch: number;
  star_count_approx: number;
  size_bytes: number;
  min_fov_deg: number;
  mag_limit: number;
}

export interface CatalogDownloadProgress {
  phase: 'tier' | 'downloading' | 'verifying' | 'extracting' | 'complete' | 'error';
  current: number;
  total: number;
  percent: number;
  tierDensity: number;
  tierIndex: number;
  nTiers: number;
}

export interface AutofindProgressEvent {
  frame_id: number;
  current: number;
  total: number;
  status: AutofindStatus;
  designation: string | null;
  distance_deg: number | null;
  /** "contains" or "nearest" when status === "labeled"; null otherwise. */
  reason: "contains" | "nearest" | null;
  /** Frame's RA/Dec at the moment of the lookup, if available. */
  frame_ra: number | null;
  frame_dec: number | null;
  /** On status === "no_match", the designation of the nearest DSO regardless
   *  of tolerance. Populated so the UI can explain why the match failed
   *  ("closest was M 31 at 0.38°, outside 0.2° tolerance"). */
  closest_designation: string | null;
  closest_distance_deg: number | null;
}

export interface AutofindCompleteEvent {
  total: number;
  labeled: number;
  no_match: number;
  already_labeled: number;
  missing_coords: number;
  errors: number;
  cancelled: boolean;
  total_time_ms: number;
}

// ============================================================================
// analysis-config.ts TS-ONLY material
// ============================================================================

/** Default annotation settings matching rustafits defaults */
export const DEFAULT_ANNOTATION_SETTINGS: AnnotationSettings = {
  color_scheme: 'eccentricity',
  show_direction_tick: true,
  ellipse_scale: 1.2,
  min_radius: 6.0,
  max_radius: 60.0,
  line_width: 2,
  ecc_good: 0.5,
  ecc_warn: 0.6,
  fwhm_good: 1.3,
  fwhm_warn: 2.0,
};
